package com.carbonfootprint.entity;
public enum TicketCategory {
    ACCOUNT, AUTHENTICATION, PASSWORD_RESET, PROFILE, ACTIVITY_LOGGING, 
    CARBON_CALCULATION, ANALYTICS, GOALS, LEADERBOARD, BADGES, 
    RECOMMENDATIONS, NOTIFICATIONS, PERFORMANCE, BUG_REPORT, 
    FEATURE_REQUEST, BILLING_FUTURE, GENERAL_SUPPORT, OTHER
}
