import React, { useState, useEffect } from 'react';
import { Lightbulb, TrendingDown, Activity, Sparkles, ChevronRight, Zap } from 'lucide-react';
import RecommendationService from '../services/RecommendationService';

const Recommendations = () => {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [activeTab, setActiveTab] = useState('Daily');

  useEffect(() => {
    const fetchRecommendations = async () => {
      try {
        const response = await RecommendationService.getPersonalizedRecommendations();
        if (response) {
          setRecommendations(response);
        } else {
          setError('Failed to fetch recommendations');
        }
      } catch (err) {
        setError(err.message || 'An error occurred');
      } finally {
        setLoading(false);
      }
    };
    fetchRecommendations();
  }, []);

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8 animate-fade-in pb-24">
      {/* Header Section */}
      <div className="flex justify-between items-center bg-white/70 backdrop-blur-xl border border-white/20 p-8 rounded-3xl shadow-sm">
        <div>
          <h1 className="text-4xl font-bold text-slate-800 tracking-tight flex items-center gap-3">
            <Sparkles className="text-indigo-500 w-10 h-10" />
            AI Intelligence
          </h1>
          <p className="text-slate-500 mt-2 text-lg max-w-2xl">
            Hyper-personalized, data-driven strategies generated by Gemini AI to minimize your carbon footprint based on your actual 30-day activity.
          </p>
        </div>
      </div>

      {/* Main Content */}
      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[1, 2, 3].map((i) => (
            <div key={i} className="bg-white/50 backdrop-blur-md p-6 rounded-3xl border border-white/20 h-64 animate-pulse flex flex-col justify-between">
              <div className="h-6 bg-slate-200 rounded w-1/3 mb-4"></div>
              <div className="space-y-3">
                <div className="h-4 bg-slate-200 rounded w-full"></div>
                <div className="h-4 bg-slate-200 rounded w-5/6"></div>
                <div className="h-4 bg-slate-200 rounded w-4/6"></div>
              </div>
              <div className="h-10 bg-slate-200 rounded-xl w-full mt-4"></div>
            </div>
          ))}
        </div>
      ) : error ? (
        <div className="bg-rose-50 border border-rose-200 text-rose-700 p-6 rounded-3xl text-center">
          <p className="text-lg font-medium">Unable to load AI Insights</p>
          <p className="text-sm mt-1">{error}</p>
        </div>
      ) : recommendations.length === 0 ? (
        <div className="bg-white/50 backdrop-blur-md p-12 rounded-3xl border border-white/20 text-center">
          <Lightbulb className="w-16 h-16 text-slate-300 mx-auto mb-4" />
          <h3 className="text-xl font-semibold text-slate-700 mb-2">Need More Data</h3>
          <p className="text-slate-500">Log more activities to generate highly personalized AI recommendations.</p>
        </div>
      ) : (
        <div className="space-y-8">
          {/* Tabs */}
          <div className="flex flex-wrap gap-2 justify-center bg-white/40 backdrop-blur-md p-2 rounded-2xl border border-white/20 shadow-sm w-fit mx-auto">
            {['Daily', 'Weekly', 'Monthly', 'Yearly'].map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-6 py-2.5 rounded-xl text-sm font-bold transition-all duration-300 ${
                  activeTab === tab
                    ? 'bg-indigo-600 text-white shadow-md'
                    : 'text-slate-500 hover:text-indigo-600 hover:bg-white/60'
                }`}
              >
                {tab} Actions
              </button>
            ))}
          </div>

          {/* Cards Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 animate-fade-in" key={activeTab}>
            {recommendations.map((rec, index) => {
              const tipContent = 
                activeTab === 'Daily' ? rec.dailyTip :
                activeTab === 'Weekly' ? rec.weeklyTip :
                activeTab === 'Monthly' ? rec.monthlyTip :
                rec.yearlyTip;

              const badgeColor = 
                activeTab === 'Daily' ? 'text-emerald-600 bg-emerald-50' :
                activeTab === 'Weekly' ? 'text-blue-600 bg-blue-50' :
                activeTab === 'Monthly' ? 'text-purple-600 bg-purple-50' :
                'text-amber-600 bg-amber-50';

              const iconColor = 
                activeTab === 'Daily' ? 'text-emerald-500 bg-emerald-100' :
                activeTab === 'Weekly' ? 'text-blue-500 bg-blue-100' :
                activeTab === 'Monthly' ? 'text-purple-500 bg-purple-100' :
                'text-amber-500 bg-amber-100';

              const gradientClass = 
                activeTab === 'Daily' ? 'from-emerald-500/20 to-teal-500/20 group-hover:bg-emerald-500/30' :
                activeTab === 'Weekly' ? 'from-blue-500/20 to-cyan-500/20 group-hover:bg-blue-500/30' :
                activeTab === 'Monthly' ? 'from-purple-500/20 to-fuchsia-500/20 group-hover:bg-purple-500/30' :
                'from-amber-500/20 to-orange-500/20 group-hover:bg-amber-500/30';

              return (
                <div key={index} className="group bg-white/70 backdrop-blur-xl border border-white/20 p-8 rounded-3xl shadow-sm hover:shadow-xl transition-all duration-300 hover:-translate-y-1 relative overflow-hidden flex flex-col h-full">
                  
                  {/* Dynamic Gradient Background Accent */}
                  <div className={`absolute top-0 right-0 -mr-16 -mt-16 w-32 h-32 bg-gradient-to-br ${gradientClass} rounded-full blur-3xl transition-all duration-500`}></div>

                  <div className="flex items-center gap-3 mb-6 relative z-10">
                    <div className={`p-3 rounded-2xl ${iconColor}`}>
                      <Activity className="w-6 h-6" />
                    </div>
                    <div>
                      <h3 className="font-bold text-slate-800 text-xl capitalize">{rec.activity}</h3>
                      <span className={`text-xs font-bold px-2.5 py-1 rounded-lg uppercase tracking-wider ${badgeColor}`}>
                        Top Priority
                      </span>
                    </div>
                  </div>

                  <div className="flex-grow relative z-10 mb-8 flex items-center">
                    <p className="text-slate-700 leading-relaxed text-lg font-medium">
                      {tipContent || rec.recommendation}
                    </p>
                  </div>

                  <div className="mt-auto relative z-10 pt-6 border-t border-slate-100 flex items-center justify-between">
                    <div>
                      <p className="text-xs text-slate-400 font-bold uppercase tracking-wider mb-1">Impact</p>
                      <div className="flex items-center gap-2 text-emerald-600 font-bold text-lg">
                        <TrendingDown className="w-5 h-5" />
                        <span>-{rec.reductionPercentageTarget}% CO₂</span>
                      </div>
                    </div>
                    
                    <button className="flex items-center gap-1 bg-slate-900 text-white px-5 py-2.5 rounded-xl font-medium hover:bg-indigo-600 transition-colors shadow-sm group/btn">
                      Apply
                      <ChevronRight className="w-4 h-4 group-hover/btn:translate-x-1 transition-transform" />
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
          
          <div className="bg-white/40 backdrop-blur-md p-6 rounded-3xl border border-white/20 mt-8">
             <div className="flex items-center gap-3 mb-2">
                <Lightbulb className="w-5 h-5 text-indigo-500" />
                <h4 className="font-bold text-slate-800 text-lg">Overall Context</h4>
             </div>
             <div className="space-y-3">
               {recommendations.map((rec, idx) => (
                 <p key={idx} className="text-slate-600 text-sm">
                   <span className="font-bold capitalize text-slate-700">{rec.activity}:</span> {rec.recommendation}
                 </p>
               ))}
             </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Recommendations;
