import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Clean old caches automatically
cleanupOutdatedCaches();

// Precache static assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Setup Background Sync for pending offline activity submissions
const activitySyncPlugin = new BackgroundSyncPlugin('activityQueue', {
  maxRetentionTime: 24 * 60 // Retry for max of 24 Hours (specified in minutes)
});

// Cache Images (Cache First — images don't change often)
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// REAL-TIME DATA: Never cache live user metrics — always go to network
// This covers: dashboard, analytics, leaderboard, goals, carbon metrics
registerRoute(
  ({ url }) =>
    url.pathname.startsWith('/api/v1/carbon/metrics') ||
    url.pathname.startsWith('/api/v1/leaderboard') ||
    url.pathname.startsWith('/api/v1/goals') ||
    url.pathname.startsWith('/api/v1/activities/history'),
  new NetworkOnly()
);

// STABLE READ-ONLY DATA: Catalog, badges, recommendations (StaleWhileRevalidate for speed)
// These change only on admin action — safe to serve cached version while fetching fresh
registerRoute(
  ({ url }) =>
    url.pathname.startsWith('/api/v1/activities/catalog') ||
    url.pathname.startsWith('/api/v1/badges') ||
    url.pathname.startsWith('/api/v1/recommendations'),
  new StaleWhileRevalidate({
    cacheName: 'stable-api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 6 * 60 * 60, // 6 Hours
      }),
    ],
  })
);

// USER PROFILE: Network First with short-lived cache fallback for offline resilience
registerRoute(
  ({ url }) =>
    url.pathname.startsWith('/api/v1/users/') &&
    !url.pathname.startsWith('/api/v1/auth/'),
  new NetworkFirst({
    cacheName: 'profile-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 5,
        maxAgeSeconds: 60 * 60, // 1 Hour
      }),
    ],
    networkTimeoutSeconds: 4,
  })
);

// Background sync for offline activity POST requests
registerRoute(
  ({ url, request }) => url.pathname.includes('/api/v1/carbon/activities') && request.method === 'POST',
  new NetworkFirst({
    plugins: [activitySyncPlugin],
  })
);

// SPA Navigation fallback — NetworkFirst ensures we serve the latest app shell
registerRoute(
  new NavigationRoute(
    new NetworkFirst({
      cacheName: 'navigations',
      plugins: [
        new ExpirationPlugin({
          maxEntries: 10,
          maxAgeSeconds: 24 * 60 * 60,
        }),
      ],
      networkTimeoutSeconds: 3,
    })
  )
);

// Listen for messages to completely wipe the cache on logout
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'CLEAR_CACHES') {
    caches.keys().then((cacheNames) => {
      cacheNames.forEach((cacheName) => {
        caches.delete(cacheName);
      });
    });
  }
});

